# All about pandas

- *first of all you have to install pandas lib*
- *take this command* **[pip install pandas]**

In [2]:
import pandas as pd

In [6]:
df = pd.read_csv('orders.csv')
df.head()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico

In [ ]:
# another way to read file in pandas => to add path of the file 
df= pd.read_csv("C:\My_github\Python_for_DataScience\orders.csv")
df.head()

<>:2: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
<>:2: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
C:\Users\Msi ETC\AppData\Local\Temp\ipykernel_4968\736774726.py:2: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
  df= pd.read_csv("C:\My_github\Python_for_DataScience\orders.csv")

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico

In [9]:
# function head() enable you to display number of rows you want 
df.head(7)

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK

In [10]:
# if you wanna to display x number of rows from the buttom 
df.tail(4)

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [ ]:
df.dtypes # this function show you data type for each column

OrderID           int64
CustomerName        str
Product             str
Category            str
Quantity          int64
Price           float64
OrderDate           str
Shipped             str
Country             str
dtype: object

In [ ]:
df.to_excel("order.xlsx",sheet_name='invantory',index=False)

8The to_excel() method stores the data as an excel file. In the example here, the sheet_name is named passengers instead of the default Sheet1. By setting index=False the row index labels are not saved in the spreadsheet.*

In [16]:
df = pd.read_excel("order.xlsx",sheet_name="invantory")
df.head()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico

In [19]:
#The method info() provides technical information about a DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       40 non-null     int64
 1   CustomerName  40 non-null     str
 2   Product       40 non-null     str
 3   Category      40 non-null     str
 4   Quantity      40 non-null     int64
 5   Price         40 non-null     float64
 6   OrderDate     40 non-null     str
 7   Shipped       40 non-null     str
 8   Country       40 non-null     str
dtypes: float64(1), int64(2), str(6)
memory usage: 2.9 KB

In [ ]:
df.describe() # describe() function show summary statistic about you dataset

           OrderID    Quantity        Price
count    40.000000   40.000000    40.000000
mean   1020.500000    5.450000   106.457500
std      11.690452   15.903475   201.091854
min    1001.000000    1.000000     0.800000
25%    1010.750000    1.000000    18.000000
50%    1020.500000    1.000000    43.500000
75%    1030.250000    2.250000   112.500000
max    1040.000000  100.000000  1200.000000

In [24]:
## if wanna access spacific column
names = df["CustomerName"]
names.head()

0       John Smith
1        Sarah Lee
2         Ali Khan
3       Alice Wong
4    Carlos Mendez
Name: CustomerName, dtype: str

***Each column in a DataFrame is a Series. As a single column is selected, the returned object is a pandas Series.***

In [25]:
type(names)

pandas.Series

In [ ]:
names.shape # shape attribute show you the num of rows and num of columns 
## notice that the default is one 1

(40,)

In [28]:
df.shape

(40, 9)

##### what about if you wanna to select subset of data or more than one column

In [32]:
impinfo= df[['Product','Price']] ## notice you have to add two squar brackets if you wanna select multiple columns
impinfo.head()

        Product   Price
0        Laptop  1200.0
1    Headphones   150.0
2  Office Chair   300.0
3     Desk Lamp    45.0
4      Keyboard    80.0

In [ ]:
# the output is dataframe not series
type(impinfo)

pandas.DataFrame

In [35]:
impinfo.shape

(40, 2)

In [39]:
# now you wanna to return spacific data from the spacific data you have selected
price_up_100=impinfo[impinfo['Price']>100.]
price_up_100.head()

         Product   Price
0         Laptop  1200.0
1     Headphones   150.0
2   Office Chair   300.0
6  Standing Desk   450.0
7        Monitor   220.0

In [ ]:
price_up_100=df[df['Price']>100]  ## df['Price']>100 ==> this like a condition
price_up_100.head()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea

In [46]:
is_up_100=df['Price']>100 ## here you are asking if the price is ubove 100
is_up_100.head()

0     True
1     True
2     True
3    False
4    False
Name: Price, dtype: bool

**To filter the rows based on such a function, use the conditional function inside the selection brackets []. In this case, the condition inside the selection brackets df["Country"].isin(['USA', 'Canada']) checks for which rows the Country column is either 'USA' or 'Canada'**

In [ ]:
class_USA_Cand = df[df["Country"].isin(['USA','Canada'])]
class_USA_Cand

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [ ]:
class_USA_Cand = df[(df['Country']=='USA')|(df['Country']=='Canada')]
class_USA_Cand

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

*When combining multiple conditional statements, each condition must be surrounded by parentheses (). Moreover, you can not use or/and but need to use the or operator | and the and operator &.*

**The notna() conditional function returns a True for each row the values are not a Null value. As such, this can be combined with the selection brackets [] to filter the data table.**

In [52]:
not_null = df[df['OrderDate'].notna()]
not_null.head()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico

***How do I select specific rows and columns from a DataFrame?***

#### **loc vs iloc in Pandas — In Depth**

- loc → selects using labels/names
- iloc → selects using integer positions

In [55]:
print(df.loc[1,'Price']) #[row,column]

150.0

**Give me the value whose label is 1 and whose column label is "price"**

In [56]:
# if you know the order or the index of the column you can do that 
print(df.iloc[1,5])

150.0

In [58]:
ndf = pd.DataFrame({
    "name": ["Ali", "Ahmed", "Omar", "Mona"],
    "age": [20, 22, 21, 23],
    "city": ["Cairo", "Giza", "Luxor", "Aswan"]
})

ndf

    name  age   city
0    Ali   20  Cairo
1  Ahmed   22   Giza
2   Omar   21  Luxor
3   Mona   23  Aswan

In [60]:
# if i wanna select spacific row 
print(ndf.loc[1])

name    Ahmed
age        22
city     Giza
Name: 1, dtype: object

In [ ]:
ndf.loc[[1,2]] # select rows  1 and  2

    name  age   city
1  Ahmed   22   Giza
2   Omar   21  Luxor

**Selecting columns with loc**

In [ ]:
ndf.loc[:,'age'] # the " : " -> means all rows

0    20
1    22
2    21
3    23
Name: age, dtype: int64

**selecting multiple columns with loc**

In [64]:
ndf.loc[:,['name','age']]

    name  age
0    Ali   20
1  Ahmed   22
2   Omar   21
3   Mona   23

**selecting multiple rows and multiple columns**

In [65]:
ndf.loc[[1,3],['name','age']]

    name  age
1  Ahmed   22
3   Mona   23

In [ ]:
ndf.loc[1:3,['name','age']] # you have to notice that 3 is included

    name  age
1  Ahmed   22
2   Omar   21
3   Mona   23

In [69]:
ndf.loc[:, "name":"city"]

    name  age   city
0    Ali   20  Cairo
1  Ahmed   22   Giza
2   Omar   21  Luxor
3   Mona   23  Aswan

In [73]:
ndf[ndf['age']>21]

    name  age   city
1  Ahmed   22   Giza
3   Mona   23  Aswan

In [71]:
ndf.loc[ndf['age']>21]

    name  age   city
1  Ahmed   22   Giza
3   Mona   23  Aswan

In [ ]:
ndf.loc[ndf["age"] > 21, ["name", "age"]] # Condition + specific columns

    name  age
1  Ahmed   22
3   Mona   23

In [76]:
## multiple conditions
ndf.loc[
    (ndf["age"] > 20) & (ndf["city"] == "Giza")
]

    name  age  city
1  Ahmed   22  Giza

In [78]:
ndf.loc[
    (ndf["city"] == "Giza") | (ndf["city"] == "Cairo")
]

    name  age   city
0    Ali   20  Cairo
1  Ahmed   22   Giza

##### **loc** can modify data

In [81]:
ndf.loc[ndf["age"] > 21, "city"] = "Unknown"
ndf

    name  age     city
0    Ali   20    Cairo
1  Ahmed   22  Unknown
2   Omar   21    Luxor
3   Mona   23  Unknown

In [84]:
#Changing multiple columns
ndf.loc[ndf['age']>21,['age','city']]=[55,'A/n']
ndf

    name  age   city
0    Ali   20  Cairo
1  Ahmed   55    A/n
2   Omar   21  Luxor
3   Mona   55    A/n

### iloc() ==> means : integer location

**df.iloc[row_position, column_position]**

In [ ]:
## the key while using iloc() ==> just use index

ndf.iloc[1] ## accessing row with index 1

name    Ahmed
age        55
city      A/n
Name: 1, dtype: object

In [87]:
## accessing mutilpe rows
ndf.iloc[[1,2]]

    name  age   city
1  Ahmed   55    A/n
2   Omar   21  Luxor

In [89]:
# accessing range of rows
ndf.iloc[1:3]  # you have to notice something the with index 3 is not include as iloc deal with indexes not lables

    name  age   city
1  Ahmed   55    A/n
2   Omar   21  Luxor

In [90]:
## accessing row and columns
ndf.iloc[:,2]

0    Cairo
1      A/n
2    Luxor
3      A/n
Name: city, dtype: str

In [92]:
## multiple columns 
ndf.iloc[:,[1,2]]

   age   city
0   20  Cairo
1   55    A/n
2   21  Luxor
3   55    A/n

In [93]:
## Rows + columns
ndf.iloc[[0, 2], [0, 1]]

   name  age
0   Ali   20
2  Omar   21

|                   | `loc`           | `iloc`       |
| ----------------- | --------------- | ------------ |
| Uses              | Labels          | Positions    |
| `df.loc[1]`       | label 1         | ❌            |
| `df.iloc[1]`      | ❌               | position 1   |
| Slice ending      | **Included**    | **Excluded** |
| Conditions        | ✅               | ❌ generally  |
| Column names      | ✅               | ❌            |
| Integer positions | Not its purpose | ✅            |

### How to create new columns derived from existing columns

In [94]:
df.head()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico

In [96]:
df['total_price']=df['Price']*df['Quantity']

In [97]:
df.head()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country,total_price
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA,1200.0
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada,300.0
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE,300.0
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore,135.0
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico,160.0

### How to calculate summary statistics

In [101]:
df['Price'].mean()

np.float64(106.45750000000001)

In [102]:
df['Price'].describe()

count      40.000000
mean      106.457500
std       201.091854
min         0.800000
25%        18.000000
50%        43.500000
75%       112.500000
max      1200.000000
Name: Price, dtype: float64

**agg() function allow you to select the columns and statatical method you want**

In [103]:
df.agg(
    {
        "Price": ["min", "max", "median", "skew"],
        "Quantity": ["min", "max", "median", "mean"],
    }
)

              Price  Quantity
min        0.800000      1.00
max     1200.000000    100.00
median    43.500000      1.00
skew       4.472299       NaN
mean            NaN      5.45

**Aggregating statistics grouped by category**

In [105]:
df[['Price','Category']].groupby('Category').mean()

                  Price
Category
Electronics  140.722222
Furniture    120.571429
Stationery     4.662500

In [108]:
df.groupby("Category").mean(numeric_only=True)

                 OrderID   Quantity       Price  total_price
Category
Electronics  1020.166667   1.500000  140.722222   174.777778
Furniture    1021.857143   1.285714  120.571429   142.357143
Stationery   1018.875000  21.625000    4.662500    54.250000

In [109]:
# display the mean of the total_price group by Category & country 
df.groupby(['Category','Country'])['total_price'].mean()

Category     Country
Electronics  Brazil            95.000000
             Canada           300.000000
             France            80.000000
             Germany          140.000000
             Japan             35.000000
             Mexico           160.000000
             Morocco           32.000000
             Poland            90.000000
             Portugal         125.000000
             South Korea      195.333333
             Spain            125.000000
             Sweden            28.000000
             USA             1200.000000
Furniture    Argentina         22.000000
             China            280.000000
             Colombia          42.000000
             Germany           70.000000
             India            360.000000
             Iran              28.000000
             Italy             18.000000
             Saudi Arabia     120.000000
             Singapore        135.000000
             UAE              300.000000
             UK               259.000000
             USA               65.000000
             Ukraine           35.000000
Stationery   Australia         36.000000
             Canada            28.000000
             Egypt            160.000000
             Italy             15.000000
             Pakistan          60.000000
             Russia            30.000000
             UAE               25.000000
             USA               80.000000
Name: total_price, dtype: float64

**Count number of records by category**

*The value_counts() method counts the number of records for each category in a column.*

In [111]:
df['Category'].value_counts()

Category
Electronics    18
Furniture      14
Stationery      8
Name: count, dtype: int64

In [113]:
# you can do it using groupby
df.groupby("Category")["Category"].count()

Category
Electronics    18
Furniture      14
Stationery      8
Name: Category, dtype: int64

### VIP note:
**Both size and count can be used in combination with groupby. Whereas size includes NaN values and just provides the number of rows (size of the table), count excludes the missing values. In the value_counts method, use the dropna argument to include or exclude the NaN values.**

REMEMBER
Aggregation statistics can be calculated on entire columns or rows.

groupby provides the power of the split-apply-combine pattern.

value_counts is a convenient shortcut to count the number of entries in each category of a variable.